### ISSUE TITLE
Namespaced pages are not decorated

### ISSUE THREAD

**Issue by danyalaytekin** [fbgallet/roam-extension-ref-count#2]
Whichever namespace display mode is active, a namespaced page is not currently decorated with a reference count.

### Environment

- Extension version 1
- Roam `0.9.8-5a7c150e`
- Safari

### Examples

| Minimal | Abbreviated | Full |
| --- | --- | --- |
|  <img width="231" alt="namespaced 3" src="https://user-images.githubusercontent.com/1315042/225543055-bed9dda6-84ae-4ec4-93ab-9de21ebeae97.png"> | <img width="231" alt="namespaced 1" src="https://user-images.githubusercontent.com/1315042/225542999-879b5785-e5a1-4e5e-80f3-d3a8d49c88ff.png"> | <img width="231" alt="namespaced 2" src="https://user-images.githubusercontent.com/1315042/225543038-92b43083-28a6-4388-ae78-817158eaa3e1.png"> |

**Comment by fbgallet** [comment]
Thanks, i had not tested namespace display modes! It will be fixed in v.2.

**Comment by danyalaytekin** [comment]
I just saw this happening in my graph - thanks for implementing it.
