### ISSUE TITLE
Block & template autocomplete items are decorated with ref count of `0`

### ISSUE THREAD

**Issue by danyalaytekin** [fbgallet/roam-extension-ref-count#3]
Currently `((` autocomplete and `;;` autocomplete items seem to be getting included by accident, and they're being decorated with `0` however many references there are.

- expected solution: no decoration for either
- solution that would be awesome but which might overstep the bounds of this plugin: blocks decorated with correct number, templates not decorated
- galaxy brain solution?: get Baibhav to do it for blocks by impressing him with what you've achieved for pages

### Environment

- Extension version 1
- Roam `0.9.8-5a7c150e`
- Safari

### Examples

| No results | Some results |
| --- | --- |
| <img width="336" alt="block helper 1" src="https://user-images.githubusercontent.com/1315042/225547698-5caac1b2-5502-4549-b36b-aa0d064d252e.png"> | <img width="351" alt="block helper 2" src="https://user-images.githubusercontent.com/1315042/225547718-835b725d-de63-40a9-b65d-f9f6725c5e2a.png"> |

**Comment by fbgallet** [comment]
Thanks Danyal, it's fixed in v.2!

I thought I had already filtered out the items that were not page reference in the autocomplete box, but in fact the count did not appear because of my footnotes extension!

**Comment by fbgallet** [comment]
@danyalaytekin, concerning a possible block references count in autocomplete box, there are two problems that make it not properly feasible on the frontend:
- different blocks can have the same content and the autocomplete box doesn't provide the block uid in the DOM
- the search for the mentions of a block consumes much more resources than those of a page, it could slow down the autocomplete UX

**Comment by danyalaytekin** [comment]
> it's fixed in v.2!

Amazing, thanks @fbgallet 

> concerning a possible block references count... there are two problems

Ah I see.  Sometimes I think we might benefit from the Roam team spending a week or two making sure that useful states are surfaced into the DOM.  It's quite inconsistent at the moment.  But they probably have enough to do already
