### ISSUE TITLE
Two times same numbers on one day?

### ISSUE THREAD

**Issue by mike-leber** [fbgallet/roam-extension-ref-count#4]
I used the same tags on one day. But the counters did not go up
![image](https://user-images.githubusercontent.com/16378740/236135371-3c7ed959-b430-4dc4-84f9-2d6708471595.png)

**Comment by mike-leber** [comment]
Sorry, my fault. Only recognized now. The counter shows the total. Each time and everywhere, not the order. Sorry, my fault ;)

**Comment by mike-leber** [comment]
Sorry, my fault. Only recognized now. The counter shows the total. Each time and everywhere, not the order. Sorry, my fault ;)

**Comment by fbgallet** [comment]
@mike-leber you get it!
What can be misleading is that, when you add a page reference, the counter isn't incremented until you browse to another page/view (it's a design choice to minimize the impact of the extension each time a block is edited. On very large pages, refresh all counters could be quite "expensive" in resources.)
